name: 'semver'
description: 'Installs and runs the Altavec SemanticVersion tool'
author: 'Altavec'
inputs:
  source:
    description: 'The NuGet source that contains the tool as well as the packges to be versioned.'
  configfile:
    description: 'The NuGet configuration file to use.'
  toolVersion:
    description: 'The version of the semantic version dotnet CLI tool to install and use. If not specified, the default is the latest stable version.'
  solution:
    description: 'The path to the solution'
  isDefaultBranch:
    description: 'Whether the current branch is the default branch. Forces there to be no version suffix. This overrides versionSuffix.'
    default: 'false'
  versionSuffix:
    description: 'Sets the pre-release value. If none is specified, the pre-release from the previous version is used.'
  increment:
    description: 'Sets the location for the version increment. Can be either Patch to increment the patch value, or ReleaseLabel to increment the release label. Only valid for version >= 1.0.82'
    default: 'Patch'
  packageIdRegex:
    description: 'The regular expression to match in the package id'
    default: 'Altavec'
  packageIdReplace:
    description: 'The text used to replace the match from packageIdRegex'
    default: 'Mondo'
  workingDirectory:
    description: 'The working directory to operate in'
runs:
  using: 'node20'
  main: 'dist/index.js'
